// src/components/Footer.tsx
import Link from "next/link";
import { Row } from "./layout/grid";

export const Footer = () => {
  const year = new Date().getFullYear();
  return (
    <Row background="accent">
      <p>&copy; 2019–{year}.</p>{" "}
      <p>
        Stork is maintained by{" "}
        <Link href="https://jameslittle.me">James Little</Link>, who&apos;s
        really excited that you&apos;re checking it out.
      </p>
      <p>
        This site is open source. Please{" "}
        <Link href="https://github.com/stork-search/site">file a bug</Link> if
        you see something confusing or incorrect.
      </p>
      <p>
        Logo art by{" "}
        <Link href="https://www.instagram.com/bruno_monts/">Bruno Monts</Link>,
        with special thanks to the{" "}
        <Link href="https://fission.codes">fission.codes</Link> team.
        <br />
        Please contact James Little before using the logo for anything.
      </p>
    </Row>
  );
};

// components/footer.vue
<template>
  <section class="footer">
    <!-- <p><b>Stork</b></p> -->
    <p>&copy; 2019–{{ year }}</p>
    <p>
      Stork is built and shepherded by
      <a href="https://jameslittle.me">James Little</a>, who's really excited
      that you're checking it out. If you have any questions or comments, feel
      free to <a href="https://twitter.com/jameslittle230">get in touch</a> or
      <a href="https://github.com/jameslittle230/stork"
        >open an issue on Github.</a
      >
    </p>
  </section>
</template>

<script>
export default {
  computed: {
    year() {
      return new Date().getFullYear()
    }
  }
}
</script>

<style lang="scss" scoped>
@import '~assets/main.scss';
section {
  background-color: $accent-color;
}
</style>
