// components/footer.vue
<template>
  <section class="footer">
    <!-- <p><b>Stork</b></p> -->
    <p>&copy; 2019–{{ year }}</p>
    <p>
      Stork is built and shepherded by
      <a href="https://jameslittle.me">James Little</a>, who's really excited
      that you're checking it out. If you have any questions or comments, feel
      free to <a href="https://twitter.com/jameslittle230">get in touch</a> or
      <a href="https://github.com/jameslittle230/stork"
        >open an issue on Github.</a
      >
    </p>
  </section>
</template>

<script>
export default {
  computed: {
    year() {
      return new Date().getFullYear()
    }
  }
}
</script>

<style lang="scss" scoped>
@import '~assets/main.scss';
section {
  background-color: $accent-color;
}
</style>

// src/components/footer.tsx
import React from "react"
import styled from "styled-components"
import PropTypes from "prop-types"

import { Link } from "gatsby"

import { accentColor, Wrapper, Column } from "./utils"

const Footer = () => (
  <Wrapper background={accentColor}>
    <Column>
      <p>&copy; 2019–2020</p>
      <p>
        Stork is built and shepherded by{" "}
        <a href="https://jameslittle.me">James Little</a>, who's really excited
        that you're checking it out. If you have any questions or comments, feel
        free to <a href="https://twitter.com/jameslittle230">get in touch</a> or{" "}
        <a href="https://github.com/jameslittle230/stork">
          open an issue on Github.
        </a>
      </p>
    </Column>
  </Wrapper>
)

export default Footer
